training:
  lr: 0.01
  weight-decay: 0.0000001
  bs: 32
  scheduler: 'steplr'
  gamma: 0.1
  step-size: 15
  rebalancing_fake: 0.3
  rebalancing_real: 1
  frames-per-video: 20 # Equidistant frames
  
model:
  image-size: 224
  patch-size: 7
  num-classes: 1
  dim: 160
  depth: 6
  dim-head: 64
  heads: 8
  mlp-dim: 2048
  emb-dim: 392
  dropout: 0.15
  emb-dropout: 0.15
